name: Good Morning
on: push
jobs:
  send-message:
    name: send-message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - name: install dependencies
      run: npm install
    - name: send a message
      run: npm start
